### ISSUE TITLE
Statuses sometimes default in some places

### ISSUE THREAD

**Issue by sheeepdev** [izutsumi/nordDiscord#4]
The recolored statuses are sometimes the default color in some places (for example when in dms and look at the top then its default sometimes) @idislikechair could u fix this

**Comment by IDislikeChair** [comment]
I am taking a look at it, but I cannot reproduce the problem at the moment. Would you mind sending some screenshots of the default color statuses if you see one?

**Comment by sheeepdev** [comment]
![jFDSy7msLY](https://user-images.githubusercontent.com/68562536/105634039-66d26a00-5e5c-11eb-8c7a-9a828daee5e7.png)
![Discord_MRw5lvkPCH](https://user-images.githubusercontent.com/68562536/105634040-68039700-5e5c-11eb-8137-d4ee41e5bfcd.png)

**Comment by sheeepdev** [comment]
you see on the first picture its the nord color and on the second it isnt

**Comment by sheeepdev** [comment]
also when someone is typing and stopped typing its reset to default

**Comment by IDislikeChair** [comment]
It works fine on my machine but I think I know what is the cause of this problem now. I will fix it by tmr.
https://user-images.githubusercontent.com/68640628/105665200-15cc7f80-5f09-11eb-8c68-aa75fafebd61.mp4

**Comment by IDislikeChair** [comment]
It works fine for me, but I think I know the cause of the problem now. I will fix it by tomorrow(ish).
https://user-images.githubusercontent.com/68640628/105665378-807dbb00-5f09-11eb-9bcc-6ac034fa0c1c.mp4

**Comment by IDislikeChair** [comment]
@sheeepdev Can you check [this fork](https://github.com/IDislikeChair/nordDiscord)? If it works correctly, I will make a pull request.

**Comment by sheeepdev** [comment]
> 
> 
> @sheeepdev Can you check [this fork](https://github.com/IDislikeChair/nordDiscord)? If it works correctly, I will make a pull request.

thanks! its fixed now

**Comment by sheeepdev** [comment]
but it seems it works only on nord discord darker

**Comment by IDislikeChair** [comment]
Then there should still be something wrong with it because I did the same thing for both version. I will not make a pull request yet, until I can fix it. Can you send me where and what color was it default?

(Also I don't mean to be rude, but can you check if you downloaded the correct version of the light theme?)

**Comment by sheeepdev** [comment]
i think i did something wrong before, it works now you can do a pull request, but if I see other places where it doesn't appear ill comment here
