### ISSUE TITLE
Elements selected with `.da-` are broken.

### ISSUE THREAD

**Issue by IDislikeChair** [izutsumi/nordDiscord#6]
Many elements selected with `.da-somethingsomething` are broken, possibly because of some Discord CSS change.

Some elements that are broken:
* Title bar and its elements
* Unread message separator
* Mention
* Avatar status (again)
* etc.

edit: grammar

**Comment by IDislikeChair** [comment]
I will make a pull request soon.
(If this thing breaks again next week, I am committing Seppuku)

**Comment by IDislikeChair** [comment]
Fixed

**Comment by sheeepdev** [comment]
yey its fixed
